/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CvRouteImport } from './routes/cv'
import { Route as MonthlyMusicRecommendationRouteImport } from './routes/monthly-music-recommendation'
import { Route as PlantATreeRouteImport } from './routes/plant-a-tree'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProjectEmpiricalAssetPricingRouteImport } from './routes/project.empirical-asset-pricing'
import { Route as ProjectLearningMachinesRouteImport } from './routes/project.learning-machines'
import { Route as ProjectMathematicalStudiesRouteImport } from './routes/project.mathematical-studies'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyMusicRecommendationRoute =
  MonthlyMusicRecommendationRouteImport.update({
    id: '/monthly-music-recommendation',
    path: '/monthly-music-recommendation',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlantATreeRoute = PlantATreeRouteImport.update({
  id: '/plant-a-tree',
  path: '/plant-a-tree',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectEmpiricalAssetPricingRoute =
  ProjectEmpiricalAssetPricingRouteImport.update({
    id: '/project/empirical-asset-pricing',
    path: '/project/empirical-asset-pricing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectLearningMachinesRoute = ProjectLearningMachinesRouteImport.update({
  id: '/project/learning-machines',
  path: '/project/learning-machines',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectMathematicalStudiesRoute =
  ProjectMathematicalStudiesRouteImport.update({
    id: '/project/mathematical-studies',
    path: '/project/mathematical-studies',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/cv': typeof CvRoute
  '/monthly-music-recommendation': typeof MonthlyMusicRecommendationRoute
  '/plant-a-tree': typeof PlantATreeRoute
  '/projects': typeof ProjectsRoute
  '/project/empirical-asset-pricing': typeof ProjectEmpiricalAssetPricingRoute
  '/project/learning-machines': typeof ProjectLearningMachinesRoute
  '/project/mathematical-studies': typeof ProjectMathematicalStudiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/cv': typeof CvRoute
  '/monthly-music-recommendation': typeof MonthlyMusicRecommendationRoute
  '/plant-a-tree': typeof PlantATreeRoute
  '/projects': typeof ProjectsRoute
  '/project/empirical-asset-pricing': typeof ProjectEmpiricalAssetPricingRoute
  '/project/learning-machines': typeof ProjectLearningMachinesRoute
  '/project/mathematical-studies': typeof ProjectMathematicalStudiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/cv': typeof CvRoute
  '/monthly-music-recommendation': typeof MonthlyMusicRecommendationRoute
  '/plant-a-tree': typeof PlantATreeRoute
  '/projects': typeof ProjectsRoute
  '/project/empirical-asset-pricing': typeof ProjectEmpiricalAssetPricingRoute
  '/project/learning-machines': typeof ProjectLearningMachinesRoute
  '/project/mathematical-studies': typeof ProjectMathematicalStudiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/cv'
    | '/monthly-music-recommendation'
    | '/plant-a-tree'
    | '/projects'
    | '/project/empirical-asset-pricing'
    | '/project/learning-machines'
    | '/project/mathematical-studies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/cv'
    | '/monthly-music-recommendation'
    | '/plant-a-tree'
    | '/projects'
    | '/project/empirical-asset-pricing'
    | '/project/learning-machines'
    | '/project/mathematical-studies'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/cv'
    | '/monthly-music-recommendation'
    | '/plant-a-tree'
    | '/projects'
    | '/project/empirical-asset-pricing'
    | '/project/learning-machines'
    | '/project/mathematical-studies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CvRoute: typeof CvRoute
  MonthlyMusicRecommendationRoute: typeof MonthlyMusicRecommendationRoute
  PlantATreeRoute: typeof PlantATreeRoute
  ProjectsRoute: typeof ProjectsRoute
  ProjectEmpiricalAssetPricingRoute: typeof ProjectEmpiricalAssetPricingRoute
  ProjectLearningMachinesRoute: typeof ProjectLearningMachinesRoute
  ProjectMathematicalStudiesRoute: typeof ProjectMathematicalStudiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly-music-recommendation': {
      id: '/monthly-music-recommendation'
      path: '/monthly-music-recommendation'
      fullPath: '/monthly-music-recommendation'
      preLoaderRoute: typeof MonthlyMusicRecommendationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plant-a-tree': {
      id: '/plant-a-tree'
      path: '/plant-a-tree'
      fullPath: '/plant-a-tree'
      preLoaderRoute: typeof PlantATreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/empirical-asset-pricing': {
      id: '/project/empirical-asset-pricing'
      path: '/project/empirical-asset-pricing'
      fullPath: '/project/empirical-asset-pricing'
      preLoaderRoute: typeof ProjectEmpiricalAssetPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/learning-machines': {
      id: '/project/learning-machines'
      path: '/project/learning-machines'
      fullPath: '/project/learning-machines'
      preLoaderRoute: typeof ProjectLearningMachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/mathematical-studies': {
      id: '/project/mathematical-studies'
      path: '/project/mathematical-studies'
      fullPath: '/project/mathematical-studies'
      preLoaderRoute: typeof ProjectMathematicalStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CvRoute: CvRoute,
  MonthlyMusicRecommendationRoute: MonthlyMusicRecommendationRoute,
  PlantATreeRoute: PlantATreeRoute,
  ProjectsRoute: ProjectsRoute,
  ProjectEmpiricalAssetPricingRoute: ProjectEmpiricalAssetPricingRoute,
  ProjectLearningMachinesRoute: ProjectLearningMachinesRoute,
  ProjectMathematicalStudiesRoute: ProjectMathematicalStudiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
